### ISSUE TITLE
Finish API endpoints

### ISSUE THREAD

**Issue by elchic00** [elchic00/Macros-for-geeks#15]
- Set up models, viewmodels, and database Context for endpoints
- Make user controller so that you can call all users and individual users from the database.

**Comment by CoffeeWarrior** [comment]
Should be able to select food items from our custom API

- select by user + range of dates

**Comment by elchic00** [comment]
- Make the diary controller able to enter entries to the database

**Comment by elchic00** [comment]
Add methods and controller to get diary entries by date

**Comment by elchic00** [comment]
Add methods and controller to get diary entries by user

**Comment by elchic00** [comment]
Set up swagger for the API user interface
